Twcss
ruby-china/homeland pull request #1342
Opened 2022-04-09 16:04 UTC by qichunren

Migrate to TailwindCSS. Work on progress.

2022-04-11 04:37 UTC, huacnlee requested changes

2022-04-11 04:37 UTC, huacnlee commented on app/views/topics/_topic_sidebar.html.erb
> +  <div class="card mb-4">
这种应该在外框用 sapce-y-4

2022-04-11 04:37 UTC, huacnlee commented on app/views/topics/_node_info.html.erb
> +    <div class="container mx-auto">
container 可以考虑默认带 mx-auto

2022-04-11 04:37 UTC, huacnlee commented on app/views/topics/index.html.erb
> +  <div class="w-full sm:w-1/4">
sidebar 可以定义 css，用 apply 集成

2022-04-11 14:51 UTC, qichunren commented on app/views/topics/index.html.erb
> +  <div class="w-full sm:w-1/4">
先暂不自定class name，尽量少用apply, 打算完全改好了后, 稳定后，再进行一些封装。

2022-04-11 14:56 UTC, qichunren commented on app/views/topics/_topic_sidebar.html.erb
> +  <div class="card mb-4">
可以先不改么？感觉这样更灵活一点啊。在可控范围内。

2022-04-12 01:06 UTC, huacnlee commented on app/views/topics/_topic_sidebar.html.erb
> +  <div class="card mb-4">
Ok 那先这样

2022-04-21 14:19 UTC, qichunren commented
要完全移除bootstrap，需要改动的太多了，先这样一步一步来吧。我目前主要改动是布局和card等采用TailwindCSS的写法。×
* row/col这样的布局采用更方便的flex方法
* card这个采用`p-4 bg-white rounded`代替

其它的后面慢慢改吧，我尽量兼容了目前的页面设计，没有做过多的改动。

2022-04-21 16:24 UTC, qichunren commented
切换到暗黑模式下，顶部的样式还有一些问题。

2022-04-26 11:44 UTC, merged